### PR TITLE
@since and @until

### PR DESCRIPTION
**Pull request by stevegal**
this is based on @f1yegor commits - I couldn't get his stuff in cleanly, so I reworked it onto this and added some tests.

@f1yegor - hope you don't mind. Sorry I couldn't get it in from your fork.

### CODE REVIEW

**Comment by oleander** [comment]
Nice. I'll take a look at it during next week.

**Comment by oleander** [comment]
Thanks for your pull request.

The spec seam to pass, but git shows a message saying `fatal: no such path example in 88aac385b7eb28b2832d10f193baa321af08c398` which is caused by `git ls-tree` listing all files in master, while `git blame` is working with `88aac385b7eb28b2832d10f193baa321af08c398`.

So when running this

``` ruby
GitFame::Base.new({
  repository: @repository,
  until:"2012-03-01",
  since:"2012-02-25"
})}
```

 `git ls-tree` lists a file called `example` which didn't exist back in 2012-02-25, thus leading to  `git blame 88aac385b7eb28b2832d10f193baa321af08c398 --line-porcelain -- 'example` trying to "blame" a file that isn't there @ commit  `88aac385b7eb28b2832d10f193baa321af08c398`.

I've merged your branch with master and pushed to a branch called `stevegal-master`. Could you see if this can be fixed? Thanks!

**Comment by oleander** [comment]
Just released version 1.7.0. It's on Github master and rubygems. See if you can merge your version with mine and we can take it from there :)

**Comment by stevegal** [comment]
Re: no such file. Think this should be easy to correct if ls-tree takes the revision ID as argument - I just ignored that error as it doesn't effect the result, but it's a bit nasty and should be fixed. Hopefully I'll find some time tonight.

**Comment by stevegal** [comment]
I've added that correction into the git ls-tree. No unexpected files now!
I've done the PR into the stevegal-master branch as well. Hope that's what you need.

**Comment by oleander** [comment]
Merged you changes into `before-after`.  Just need to check the specs before I merge it into master.

**Comment by stevegal** [comment]
has a look at the branch - much neater than my effort! I think you can remove the @since and @until as it looks like you've replaced with @before and @after (does the same thing on rev-list).

**Comment by oleander** [comment]
The solution found in `before-after` is actually your code, à la Linus. I merged your other pull request into `before-after`, but isn't for some reason visible in the history, which is why I merged it again afterwards to give you some credit. Even tho you had some glitches (mostly edge cases) in your implementation, I couldn't have written mine without your code. 

I renamed it after a few hours (to before/after) as I couldn't wrap my head around until/since. Took me 5-10 sec every time I had to figure our what they ment which really bugged me. Just did a global find and replace. Hope that's okay.

Could you try it and see if the numbers make sense? I've done a lot of manual verification on the them, but they might still be off.

Note that the commits specified by `--after` aren't included in contrast to `--before` which include them. Here's an example using `--after='2010-04-26'` and `--before='2010-04-27'`. It selects all commits **after** 2010-04-26 but includes all commits in 2010-04-27. (the highlighted hashes defines the start and stop commit). This is apparently how git works, so nothing to do about it. Even tho it took me quite some time to figure out it sort of make sense.

skarmavbild 2016-05-19 kl 16 57 43

Wrote this bash script to visualize it better.

``` bash
echo "----- START ------"
# Exclude this day (choses latest commit)
echo "after 2010-04-26"
after="$(git rev-list --after='2010-04-26' --first-parent master --reverse --no-merges | head -1)"
short_after="${after:0:7}"
echo $short_after

# Choses the oldest commits this day
echo "before 2010-04-27"
before=`git rev-list --before='2010-04-27' --first-parent --no-merges master | head -1`
short_before="${before:0:7}"
echo $short_before

echo "----- LOG ------"
git log --no-merges --first-parent | nl | grep -e $short_before -e $short_after -A 5 -B 5

echo "----- SHORTLOG ------"
git shortlog $short_after..$short_before -se

echo "------ SHORTLOG DETAILS ----------"
git shortlog $short_after..$short_before

echo "------ FILES ------"
git log --name-status $short_after..$short_before
```

Before I merge this into master I need to clean up the code a bit by adding comments, refactor and add the above explanation into the readme.

**Comment by oleander** [comment]
Deployed in 2.0.0.

```
gem cleanup git_fame
gem install git_fame --version 2.0.0
```

**Pull request merged**
