### PR TITLE
since-until flags

### PR DESCRIPTION
**Pull request by f1yegor**
I believe that this time I created clear PR. Sorry for previous tries.

### CODE REVIEW

**Comment by f1yegor** [comment]
PR #24 and #25 could be removed I think

**Comment by scottconnerly** [comment]
Yes please. Would love this PR to be accepted.

**Comment by pedrokost** [comment]
This would be very useful!

**Comment by oleander** [comment]
@f1yegor Sorry about the delay. I've been super bussy over the summer. Could you make sure that the specs passes? Currently 5 of then fails. Don't forget to run `git submodule update` before running the specs, otherwise you wont run them against the fixture repo. Make sure that `master` passes before you get started, if it doesn't something is wrong with the submodule update. Thanks!

**Comment by shea256** [comment]
Hey I'd love to see this incorporated as well.

@f1yegor did you get around to addressing the failed tests?

@oleander I assume we're still waiting on this?

**Comment by f1yegor** [comment]
@shea256 nope. your help are welcome

**Comment by TafThorne** [comment]
Well I am stuck.  I don't use github much so I am not that clear of the operations but I managed to clone both the oleander and f1yegor repositories and get to the since-until branch.  This is where I got stuck though.  

I have no experience with rspec and have not managed to work out how to run the tests yet.  I am running on Ubuntu 14.04 which gives me Ruby 1.9.1.  I did not have rspec, rakeor bundle installed initially but I think I have got those in place now.  As with most simple things there is a lot of initial setup or tooling going on to make them simple.  

When I run `rspec spec` in the working area of either repository I not see something like:
```
git-fame-rb$ rspec spec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/var/lib/gems/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/formatters/documentation_formatter.rb:1:in `<top (required)>': undefined method `require_rspec_core' for RSpec::Support:Module (NoMethodError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1084:in `built_in_formatter'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:573:in `add_formatter'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration_options.rb:78:in `block in load_formatters_into'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration_options.rb:78:in `each'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration_options.rb:78:in `load_formatters_into'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration_options.rb:28:in `configure'
	from /usr/lib/ruby/vendor_ruby/rspec/core/command_line.rb:21:in `run'
	from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:80:in `run'
	from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:17:in `block in autorun'
[Coveralls] Outside the CI environment, not sending data.
```

I do not know what to do now and cannot try and fix the failing test cases if I cannot see them :-P 

Any clues what I need to do? 
````
$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
$ rspec -v 
2.14.7
$ bundle -v
Bundler version 1.3.5
$ rake --version
rake, version 10.0.4
````
Then we get onto the question of whether I have a mechanism to get from my checkout of f1yegor's repo to a point where I can send a push request to oleander's.  That would probably be obvious if I knew how to operate github.  I nothing else I guess I can fork f1yegor's then make a push request... well at least to f1yegor who seems to be online now and agian.

**Comment by oleander** [comment]
@TafThorne Try what suggested in [the readme](https://github.com/oleander/git-fame-rb#testing) :)

**Comment by TafThorne** [comment]
@oleander Is this what the output should look like?
```
$ git submodule update --init
$ rspec spec/git_fame_spec.rb
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/var/lib/gems/1.9.1/gems/rspec-core-3.4.4/lib/rspec/core/formatters/documentation_formatter.rb:1:in `<top (required)>': undefined method `require_rspec_core' for RSpec::Support:Module (NoMethodError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:1084:in `built_in_formatter'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration.rb:573:in `add_formatter'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration_options.rb:78:in `block in load_formatters_into'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration_options.rb:78:in `each'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration_options.rb:78:in `load_formatters_into'
	from /usr/lib/ruby/vendor_ruby/rspec/core/configuration_options.rb:28:in `configure'
	from /usr/lib/ruby/vendor_ruby/rspec/core/command_line.rb:21:in `run'
	from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:80:in `run'
	from /usr/lib/ruby/vendor_ruby/rspec/core/runner.rb:17:in `block in autorun'
[Coveralls] Outside the CI environment, not sending data.
```
To me that looks like I am missing a Gem or that the version I have pulled from git is broken at present? 

I had done some fiddling to see if it was a platform issue my end that I could fix.  Removing that and updating to the latest version:
```
$ git describe 
v1.5.0-7-ga7a27af
```
still gives me the same output.

**Comment by stevegal** [comment]
have you bundler installed? If not try 
`gem install bundler`
then
`bundler install`
and it'll pull in the required gems

**Comment by oleander** [comment]
@TafThorne You need to run `bundle exec rspec ...` for the test to run properly. I'll update the readme.

**Comment by TafThorne** [comment]
@stevegal Thank you for the suggestion.  I already have bundler installed by some means.  This does not seem to have been the issue I was facing.

**Comment by TafThorne** [comment]
@oleander Thank you for that suggestion.  I seem to be able to run the tests on the main branch now.  

My first attempt failed:
```
:~/work/git-fame-rb$ bundle exec rspec ...
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/var/lib/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/configuration.rb:746:in `load': cannot load such file -- /home/thomasthorne/work/git-fame-rb/... (LoadError)
	from /var/lib/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/configuration.rb:746:in `block in load_spec_files'
	from /var/lib/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/configuration.rb:746:in `map'
	from /var/lib/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/configuration.rb:746:in `load_spec_files'
	from /var/lib/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/command_line.rb:22:in `run'
	from /var/lib/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/runner.rb:69:in `run'
	from /var/lib/gems/1.9.1/gems/rspec-core-2.10.1/lib/rspec/core/runner.rb:10:in `block in autorun'
[Coveralls] Outside the CI environment, not sending data.
```
After that I remembered that I needed to specify which tests to execute:
```
:~/work/git-fame-rb$ bundle exec rspec spec/git_fame_spec.rb 
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

GitFame::Base
HEAD is now at 7ab01bc... Example commit
  #authors
    should have a list of authors
    author
      should have a bunch of commits
      should have a number of locs
      should respond to name
      should have a number of files
      should have a distribution
    format
      should format #commits
      should format #files
      should format #loc
  #pretty_print

Total number of files: 16
Total number of lines: 1,082
Total number of commits: 70
+----------------+-----+---------+-------+--------------------+
| name           | loc | commits | files | distribution       |
+----------------+-----+---------+-------+--------------------+
| Magnus Holm    | 586 | 41      | 4     | 54.2 / 58.6 / 25.0 |
| 7rans          | 360 | 6       | 10    | 33.3 / 8.6 / 62.5  |
| Linus Oleander | 136 | 23      | 7     | 12.6 / 32.9 / 43.8 |
+----------------+-----+---------+-------+--------------------+
3 rows in set

Total number of files: 16
Total number of lines: 1,082
Total number of commits: 70
+----------------+-----+---------+-------+--------------------+
| name           | loc | commits | files | distribution       |
+----------------+-----+---------+-------+--------------------+
| Magnus Holm    | 586 | 41      | 4     | 54.2 / 58.6 / 25.0 |
| 7rans          | 360 | 6       | 10    | 33.3 / 8.6 / 62.5  |
| Linus Oleander | 136 | 23      | 7     | 12.6 / 32.9 / 43.8 |
+----------------+-----+---------+-------+--------------------+
3 rows in set
    should print
  branches
    should handle existing branches
    should raise an error if branch doesn't exist
  .git_repository?
    should know if a folder is a git repository [absolute path]
    should know if a folder exists or not [absolute path]
    should know if a folder is a git repository [relative path]
    should know if a folder exists or not [relative path]
  #csv_print
name,loc,commits,files,distribution
Magnus Holm,586,41,4,54.2 / 58.6 / 25.0
7rans,360,6,10,33.3 / 8.6 / 62.5
Linus Oleander,136,23,7,12.6 / 32.9 / 43.8
    should print
    should be equal to
  total
    should respond to #loc, #commits and #files
  #command_line_arguments
    should exclude the lib folder
    should exclude non rb or rdoc files
    should break out counts by file type
    should output zero for file types the author hasn't touched
  sort
    should be able to sort #authors by name
    should be able to sort #authors by commits
    should be able to sort #authors by files

Finished in 14.2 seconds
26 examples, 0 failures

Randomized with seed 11250

[Coveralls] Outside the CI environment, not sending data.
```
So I can see that all is well on the main line.  Next I will try and get things working on the patch branch.

**Comment by TafThorne** [comment]
Well I got it all passing but it looks like it isn't doing any tests.  
```
~/work/git-fame-rb_f1yegor$ bundle exec rspec spec/spec_helper.rb 
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
No examples found.

Finished in 0.00004 seconds
0 examples, 0 failures

Randomized with seed 59225

[Coveralls] Outside the CI environment, not sending data.
```
I have also just seen pull #44 turn up which looks like it already fixes all the problems I was looking at and provides more test cases.  I guess there is noting useful for me to do here so I will leave it to @stevegal on the other pull request.

**Comment by TafThorne** [comment]
I think I managed to push my changes to my own fork too.  
https://github.com/oleander/git-fame-rb/compare/master...TafThorne:since-until
Not sure how they compare with stevegals.  I keep some of the f1yegor history but there are no new tests.  

Still it was a nice learning exorcise for me.  Let me know if there is anything more that I should attempt to do.

**Comment by oleander** [comment]
@TafThorne Try `bundle exec rspec spec/git_fame_spec.rb`, that will run all the specs for you.

**Comment by TafThorne** [comment]
@oleander That generated a bit more output including some  failures to look at.  Do you need these changes any more now that #44 by stevegal covers the since-until flags?  

I will still keep working on these changes in my own time as a learning exorcise, so I do appreciate the help.  For the record the output I get from this branch was:  
```
$ bundle exec rspec spec/git_fame_spec.rb
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

GitFame::Base
HEAD is now at 7ab01bc... Example commit
  #pretty_print

Total number of files: 0
Total number of lines: 0
Total number of commits: 70
+----------------+-----+---------+-------+------------------+-------+---------+-------+
| name           | loc | commits | files | distribution     | added | deleted | total |
+----------------+-----+---------+-------+------------------+-------+---------+-------+
| 7rans          | 0   | 6       | 0     | 0.0 / 8.6 / 0.0  | 0     | 0       | 0     |
| Linus Oleander | 0   | 23      | 0     | 0.0 / 32.9 / 0.0 | 0     | 0       | 0     |
| Magnus Holm    | 0   | 41      | 0     | 0.0 / 58.6 / 0.0 | 0     | 0       | 0     |
+----------------+-----+---------+-------+------------------+-------+---------+-------+
3 rows in set

Total number of files: 0
Total number of lines: 0
Total number of commits: 70
+----------------+-----+---------+-------+------------------+-------+---------+-------+
| name           | loc | commits | files | distribution     | added | deleted | total |
+----------------+-----+---------+-------+------------------+-------+---------+-------+
| 7rans          | 0   | 6       | 0     | 0.0 / 8.6 / 0.0  | 0     | 0       | 0     |
| Linus Oleander | 0   | 23      | 0     | 0.0 / 32.9 / 0.0 | 0     | 0       | 0     |
| Magnus Holm    | 0   | 41      | 0     | 0.0 / 58.6 / 0.0 | 0     | 0       | 0     |
+----------------+-----+---------+-------+------------------+-------+---------+-------+
3 rows in set
    should print
  #command_line_arguments
    should output zero for file types the author hasn't touched
    should exclude non rb or rdoc files
    should break out counts by file type (FAILED - 1)
    should exclude the lib folder
  .git_repository?
    should know if a folder exists or not [relative path]
    should know if a folder exists or not [absolute path]
    should know if a folder is a git repository [relative path]
    should know if a folder is a git repository [absolute path]
  #csv_print
name,loc,commits,files,distribution,added,deleted,total
7rans,0,6,0,0.0 / 8.6 / 0.0,0,0,0
Linus Oleander,0,23,0,0.0 / 32.9 / 0.0,0,0,0
Magnus Holm,0,41,0,0.0 / 58.6 / 0.0,0,0,0
    should print
    should be equal to (FAILED - 2)
  branches
    should handle existing branches
    should raise an error if branch doesn't exist
  total
    should respond to #loc, #commits and #files (FAILED - 3)
  sort
    should be able to sort #authors by commits
    should be able to sort #authors by name
    should be able to sort #authors by files
  #authors
    should have a list of authors
    author
      should respond to name (FAILED - 4)
      should have a bunch of commits (FAILED - 5)
      should have a number of locs (FAILED - 6)
      should have a number of files (FAILED - 7)
      should have a distribution (FAILED - 8)
    format
      should format #files
      should format #commits
      should format #loc

Failures:

  1) GitFame::Base#command_line_arguments should break out counts by file type
     Failure/Error: author.file_type_counts["rdoc"].should eq(23)
       
       expected: 23
            got: 0
       
       (compared using ==)
     # ./spec/git_fame_spec.rb:110:in `block (3 levels) in <top (required)>'

  2) GitFame::Base#csv_print should be equal to
     Failure/Error: subject.to_csv.should eq("name,loc,commits,files,distribution\n" \
       
       expected: "name,loc,commits,files,distribution\nMagnus Holm,586,41,4,54.2 / 58.6 / 25.0\n7rans,360,6,10,33.3 / 8.6 / 62.5\nLinus Oleander,136,23,7,12.6 / 32.9 / 43.8\n"
            got: "name,loc,commits,files,distribution,added,deleted,total\n7rans,0,6,0,0.0 / 8.6 / 0.0,0,0,0\nLinus Oleander,0,23,0,0.0 / 32.9 / 0.0,0,0,0\nMagnus Holm,0,41,0,0.0 / 58.6 / 0.0,0,0,0\n"
       
       (compared using ==)
       
       Diff:
       @@ -1,5 +1,5 @@
       -name,loc,commits,files,distribution
       -Magnus Holm,586,41,4,54.2 / 58.6 / 25.0
       -7rans,360,6,10,33.3 / 8.6 / 62.5
       -Linus Oleander,136,23,7,12.6 / 32.9 / 43.8
       +name,loc,commits,files,distribution,added,deleted,total
       +7rans,0,6,0,0.0 / 8.6 / 0.0,0,0,0
       +Linus Oleander,0,23,0,0.0 / 32.9 / 0.0,0,0,0
       +Magnus Holm,0,41,0,0.0 / 58.6 / 0.0,0,0,0
     # ./spec/git_fame_spec.rb:134:in `block (3 levels) in <top (required)>'

  3) GitFame::Base total should respond to #loc, #commits and #files
     Failure/Error: subject.files.should eq(16)
       
       expected: 16
            got: 0
       
       (compared using ==)
     # ./spec/git_fame_spec.rb:55:in `block (3 levels) in <top (required)>'

  4) GitFame::Base#authors author should respond to name
     Failure/Error: author.name.should eq("Linus Oleander")
       
       expected: "Linus Oleander"
            got: "Magnus Holm"
       
       (compared using ==)
     # ./spec/git_fame_spec.rb:15:in `block (4 levels) in <top (required)>'

  5) GitFame::Base#authors author should have a bunch of commits
     Failure/Error: author.raw_commits.should eq(23)
       
       expected: 23
            got: 41
       
       (compared using ==)
     # ./spec/git_fame_spec.rb:11:in `block (4 levels) in <top (required)>'

  6) GitFame::Base#authors author should have a number of locs
     Failure/Error: author.raw_loc.should eq(136)
       
       expected: 136
            got: 0
       
       (compared using ==)
     # ./spec/git_fame_spec.rb:19:in `block (4 levels) in <top (required)>'

  7) GitFame::Base#authors author should have a number of files
     Failure/Error: author.raw_files.should eq(7)
       
       expected: 7
            got: 0
       
       (compared using ==)
     # ./spec/git_fame_spec.rb:23:in `block (4 levels) in <top (required)>'

  8) GitFame::Base#authors author should have a distribution
     Failure/Error: author.distribution.should eq("12.6 / 32.9 / 43.8")
       
       expected: "12.6 / 32.9 / 43.8"
            got: "0.0 / 58.6 / 0.0"
       
       (compared using ==)
     # ./spec/git_fame_spec.rb:27:in `block (4 levels) in <top (required)>'

Finished in 0.64448 seconds
26 examples, 8 failures

Failed examples:

rspec ./spec/git_fame_spec.rb:109 # GitFame::Base#command_line_arguments should break out counts by file type
rspec ./spec/git_fame_spec.rb:133 # GitFame::Base#csv_print should be equal to
rspec ./spec/git_fame_spec.rb:54 # GitFame::Base total should respond to #loc, #commits and #files
rspec ./spec/git_fame_spec.rb:14 # GitFame::Base#authors author should respond to name
rspec ./spec/git_fame_spec.rb:10 # GitFame::Base#authors author should have a bunch of commits
rspec ./spec/git_fame_spec.rb:18 # GitFame::Base#authors author should have a number of locs
rspec ./spec/git_fame_spec.rb:22 # GitFame::Base#authors author should have a number of files
rspec ./spec/git_fame_spec.rb:26 # GitFame::Base#authors author should have a distribution

Randomized with seed 56314

[Coveralls] Outside the CI environment, not sending data.
```

I will do what I can to fix the reported errors.

**Comment by TafThorne** [comment]
And I can confirm that the tests all pass on the latest code from the main project branch.  At least they do once I install the scrub_rb gem which seems to be required for that test set.  Test set ends with:
```
Finished in 4.06 seconds
26 examples, 0 failures

Randomized with seed 9194
```
I will try and get my patch line up to the same standard.

**Comment by oleander** [comment]
@TafThorne In the first failing test you provided my guess is that you had an invalid git repository to test git_fame against. The tests are suppose to be ran against the gash project on commit `7ab01bc5a720`. Looks like the repository has been altered in some way and that pulling down the latest changes from GH restored it.

And yes, `scrub_rb` is a new dependency of git_fame since last night. Run bundle install and you should be ready to go (which I guess you already did).

I'll be merging #44 in a few days, but feel free to continue working on your version. Maybe try to enhance #44 after it has been merged?

**Pull request closed without merging**
