### PR TITLE
corrects the git ls to look at just files for commit since/until

### PR DESCRIPTION
**Pull request by stevegal**

### CODE REVIEW

**Comment by oleander** [comment]
Thanks! You also have to merge with master as I released a new version after `oleander:stevegal-master` as created.

**Comment by oleander** [comment]
I added some tests for the binary, could you do the same with the new arguments? Here are the tests https://github.com/oleander/git-fame-rb/blob/master/spec/bin_spec.rb

**Comment by stevegal** [comment]
I've started to merge it into your master to PR from there. Would you prefer to do this?

**Comment by stevegal** [comment]
I guess, if you accept the first PR then we can close this one and delete the branch?

**Pull request closed without merging**
