### PR TITLE
New: option --repositories

### PR DESCRIPTION
**Pull request by Dogild**
This PR adds the possibility to get statistics for several projects at the same time. It configurable through the option `--repositories`, for instance `git-fame --repositories="a*"` will compute the stats for every folders which begin with a

This should fix the issue #16 

Test has not been made yet, waiting for some review first. I'm very noob in ruby!

### CODE REVIEW

**Comment by oleander** [comment]
Nice! I'll have a look at the 22th.

**Comment by Dogild** [comment]
Any news for this one ? :)

**Comment by ahungry** [comment]
Also interested, although CI build is failing atm.

**Comment by Nyholm** [comment]
Is there anything I can do to help getting this PR merged?

**Comment by jmgarnier** [comment]
Project is still maintained, looking at commits history but I wonder if this PR will be closed or this nice feature added?

For big orgs, it seems like a nice way to get an overview

**Comment by oleander** [comment]
@jmgarnier I rewrote the gem a year ago unfortunately making this PR obsolete

**Pull request closed without merging**
